/**
 * Curated common-nickname / diminutives groups (D123).
 *
 * Each inner array is one **equivalence group** of given names that should match
 * one another. Membership is **bidirectional** — any member expands to all the
 * others — so "Bill" finds "William" and "William" finds "Bill". A name may
 * appear in several groups (e.g. "Al" → Albert *and* Alan *and* Alfred); the
 * expansion map (see `nicknames.ts`) unions every group a name belongs to.
 *
 * This is a small **bundled static asset**, curated down from the conventions of
 * the public-domain nickname/diminutives lookup
 * (`carltonnorthern/nickname-and-diminutives-lookup`, CC0) to the common
 * English/Western given names a globally-drawn-but-US-centric brotherhood
 * actually carries. It covers Western names only and does no harm to non-Western
 * names, which remain covered by phonetic matching (D123). All entries are
 * lower-cased to match the tokenizer's folded form.
 *
 * It is deliberately curated, not exhaustive: over-matching (e.g. "Jack" → both
 * John and Jackson) is tolerable given AND-across-query-tokens, the short result
 * list, and match-highlighting, and the whole layer is config-flagged so it can
 * be tuned or disabled if it proves noisy.
 */
export const NICKNAME_GROUPS: readonly (readonly string[])[] = [
  ["abel", "abe"],
  ["abraham", "abe", "bram"],
  ["adam", "ade"],
  ["albert", "al", "bert", "bertie"],
  ["alan", "al"],
  ["alexander", "alex", "al", "alec", "sandy", "xander", "lex"],
  ["alfred", "al", "alf", "alfie", "fred"],
  ["andrew", "andy", "drew"],
  ["anthony", "tony", "ant"],
  ["archibald", "archie"],
  ["arnold", "arnie"],
  ["arthur", "art", "artie"],
  ["augustus", "gus", "augie"],
  ["barnaby", "barney"],
  ["bartholomew", "bart"],
  ["benjamin", "ben", "benji", "benny"],
  ["bernard", "bernie", "barney"],
  ["bradley", "brad"],
  ["brandon", "bran"],
  ["calvin", "cal"],
  ["cameron", "cam"],
  ["carl", "karl"],
  ["charles", "charlie", "chuck", "chas", "chip"],
  ["christopher", "chris", "topher", "kit"],
  ["christian", "chris"],
  ["clarence", "clare"],
  ["clifford", "cliff"],
  ["clinton", "clint"],
  ["conrad", "con"],
  ["cornelius", "corny", "neil"],
  ["curtis", "curt"],
  ["daniel", "dan", "danny"],
  ["david", "dave", "davy"],
  ["dennis", "den", "denny"],
  ["derek", "del"],
  ["donald", "don", "donnie"],
  ["dorian", "dory"],
  ["douglas", "doug", "dougie"],
  ["duncan", "dunc"],
  ["edward", "ed", "eddie", "ted", "teddy", "ned"],
  ["edwin", "ed", "eddie"],
  ["edmund", "ed", "eddie", "ned"],
  ["edgar", "ed", "eddie"],
  ["emanuel", "manny", "manuel"],
  ["emmanuel", "manny", "manuel"],
  ["eric", "rick"],
  ["ernest", "ernie"],
  ["eugene", "gene"],
  ["francis", "frank", "frankie", "fran"],
  ["franklin", "frank", "frankie"],
  ["frederick", "fred", "freddie", "fritz"],
  ["gabriel", "gabe"],
  ["geoffrey", "geoff", "jeff"],
  ["george", "georgie"],
  ["gerald", "gerry", "jerry"],
  ["gilbert", "gil"],
  ["gordon", "gordy"],
  ["gregory", "greg"],
  ["harold", "harry", "hal"],
  ["henry", "hank", "harry", "hal"],
  ["herbert", "herb", "bert"],
  ["howard", "howie"],
  ["isaac", "ike"],
  ["jacob", "jake"],
  ["james", "jim", "jimmy", "jamie", "jem"],
  ["jeffrey", "jeff"],
  ["jerome", "jerry"],
  ["jesse", "jess"],
  ["john", "jack", "johnny", "jon", "jackie"],
  ["jonathan", "jon", "jonny", "nathan"],
  ["joseph", "joe", "joey", "jos"],
  ["joshua", "josh"],
  ["julian", "jules"],
  ["kenneth", "ken", "kenny"],
  ["lawrence", "larry", "lawrie", "laurie"],
  ["laurence", "larry", "laurie"],
  ["leonard", "leo", "len", "lenny"],
  ["leopold", "leo"],
  ["leslie", "les"],
  ["lewis", "lou"],
  ["louis", "lou", "louie"],
  ["luke", "lucas"],
  ["malcolm", "mal"],
  ["martin", "marty"],
  ["matthew", "matt", "matty"],
  ["maurice", "mo"],
  ["maxwell", "max"],
  ["maximilian", "max"],
  ["michael", "mike", "mikey", "mick", "mickey", "mitch"],
  ["mitchell", "mitch"],
  ["montgomery", "monty"],
  ["nathaniel", "nat", "nate", "nathan"],
  ["nicholas", "nick", "nicky", "cole"],
  ["norman", "norm"],
  ["oliver", "ollie"],
  ["oswald", "ozzie", "oz"],
  ["patrick", "pat", "paddy", "rick"],
  ["percival", "percy"],
  ["peter", "pete", "petey"],
  ["philip", "phil"],
  ["phillip", "phil"],
  ["quentin", "quinn"],
  ["randall", "randy"],
  ["randolph", "randy"],
  ["raymond", "ray"],
  ["reginald", "reg", "reggie"],
  ["richard", "rick", "dick", "rich", "richie", "ricky", "rickey"],
  ["robert", "rob", "bob", "bobby", "robbie", "bert"],
  ["roderick", "rod", "roddy"],
  ["rodney", "rod"],
  ["roger", "rodge"],
  ["ronald", "ron", "ronnie"],
  ["russell", "russ"],
  ["samuel", "sam", "sammy"],
  ["sebastian", "seb"],
  ["solomon", "sol"],
  ["stanley", "stan"],
  ["stephen", "steve", "stevie"],
  ["steven", "steve", "stevie"],
  ["sylvester", "sly"],
  ["terence", "terry"],
  ["theodore", "theo", "ted", "teddy"],
  ["thomas", "tom", "tommy", "thom"],
  ["timothy", "tim", "timmy"],
  ["tobias", "toby"],
  ["ulysses", "uly"],
  ["vincent", "vince", "vinny", "vin"],
  ["walter", "walt", "wally"],
  ["warren", "ren"],
  ["wesley", "wes"],
  ["wilbur", "will"],
  ["william", "will", "bill", "billy", "willy", "willie", "liam", "wills"],
  ["winston", "win"],
  ["zachary", "zach", "zack", "zac"],
];
